from django.urls import path
from .views import (
    GoogleLoginView,
    RegisterView,
    LoginView,
    ProfileView,
    ChangePasswordView,
    AdminUserListView,
    AdminSetUserRoleView,
    SuperAdminOverviewView,
    SuperAdminUserListView,
    SuperAdminSetUserRoleView,
    SuperAdminSetUserActiveView,
    RoleChangeRequestCreateView,
    MyRoleChangeRequestsView,
    PendingRoleChangeRequestsView,
    RoleChangeRequestReviewView,
    NotificationListView,
    NotificationUnreadCountView,
    NotificationMarkReadView,
    NotificationMarkAllReadView,
)

urlpatterns = [
    path("google/", GoogleLoginView.as_view(), name="google-login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("users/<int:user_id>/role/", AdminSetUserRoleView.as_view(), name="admin-set-user-role"),
    path("superadmin/overview/", SuperAdminOverviewView.as_view(), name="superadmin-overview"),
    path("superadmin/users/", SuperAdminUserListView.as_view(), name="superadmin-user-list"),
    path(
        "superadmin/users/<int:user_id>/role/",
        SuperAdminSetUserRoleView.as_view(),
        name="superadmin-set-user-role",
    ),
    path(
        "superadmin/users/<int:user_id>/active/",
        SuperAdminSetUserActiveView.as_view(),
        name="superadmin-set-user-active",
    ),
    path("role-requests/", RoleChangeRequestCreateView.as_view(), name="role-request-create"),
    path("role-requests/mine/", MyRoleChangeRequestsView.as_view(), name="role-requests-mine"),
    path(
        "role-requests/pending/",
        PendingRoleChangeRequestsView.as_view(),
        name="role-requests-pending",
    ),
    path(
        "role-requests/<int:request_id>/review/",
        RoleChangeRequestReviewView.as_view(),
        name="role-request-review",
    ),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path(
        "notifications/unread-count/",
        NotificationUnreadCountView.as_view(),
        name="notifications-unread-count",
    ),
    path(
        "notifications/<int:notification_id>/read/",
        NotificationMarkReadView.as_view(),
        name="notification-mark-read",
    ),
    path(
        "notifications/mark-all-read/",
        NotificationMarkAllReadView.as_view(),
        name="notifications-mark-all-read",
    ),
]