# Generated by Django 6.0.2 on 2026-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_change_requests_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comment_warning_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('role_change_request', 'Role change request'), ('role_change_resolved', 'Role change resolved'), ('comment_warning', 'Comment warning'), ('comment_suspension', 'Comment suspension')], max_length=40),
        ),
    ]
