# Generated by Django 6.0.2 on 2026-05-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category_post_excerpt_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='improvement_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
