# Generated by Django 6.0.2 on 2026-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image_cloudinary_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
